using System.Diagnostics;
using System.Text.Json;
using System.Text.RegularExpressions;
using Serilog;

namespace GUML.Analyzer;

/// <summary>
/// Unified catalog for Godot API metadata loaded from external JSON files.
/// Provides inheritance-aware queries for theme overrides, signals, and
/// property-signal mappings. Falls back to built-in hardcoded catalogs
/// when no external file is available.
/// </summary>
internal sealed class GodotApiCatalog
{
    private static readonly JsonSerializerOptions s_jsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        WriteIndented = true,
    };

    private readonly Dictionary<string, GodotClassInfo> _classes;

    /// <summary>The Godot version this catalog was built for, if known.</summary>
    public string? GodotVersion { get; }

    /// <summary>Whether this catalog was loaded from an external JSON file (vs. built-in fallback).</summary>
    public bool IsFromExternalFile { get; }

    /// <summary>All class names in the catalog.</summary>
    public IReadOnlyDictionary<string, GodotClassInfo> Classes => _classes;

    private GodotApiCatalog(Dictionary<string, GodotClassInfo> classes, string? godotVersion, bool isExternal)
    {
        _classes = classes;
        GodotVersion = godotVersion;
        IsFromExternalFile = isExternal;
    }

    // ══════════════════════════════════════════════════════
    //  Factory methods
    // ══════════════════════════════════════════════════════

    /// <summary>
    /// Loads a catalog from a JSON file previously generated by <see cref="GodotDocParser"/>.
    /// Returns <c>null</c> if the file does not exist or cannot be parsed.
    /// </summary>
    public static GodotApiCatalog? LoadFromFile(string jsonPath)
    {
        if (!File.Exists(jsonPath))
        {
            Log.Logger.Debug("Godot API file not found: {Path}", jsonPath);
            return null;
        }

        try
        {
            string json = File.ReadAllText(jsonPath);
            var apiDoc = JsonSerializer.Deserialize<GodotApiDocument>(json, s_jsonOptions);
            if (apiDoc?.Classes == null)
            {
                Log.Logger.Warning("Invalid Godot API file (null classes): {Path}", jsonPath);
                return null;
            }

            Log.Logger.Information(
                "Loaded Godot API catalog from {Path} (version={Version}, classes={Count})",
                jsonPath, apiDoc.GodotVersion, apiDoc.Classes.Count);

            return new GodotApiCatalog(apiDoc.Classes, apiDoc.GodotVersion, isExternal: true);
        }
        catch (Exception ex)
        {
            Log.Logger.Error(ex, "Failed to load Godot API file: {Path}", jsonPath);
            return null;
        }
    }

    /// <summary>
    /// Creates a minimal fallback catalog from the built-in
    /// <see cref="PropertySignalCatalog"/> hardcoded data.
    /// Only property→signal mappings are included; theme overrides and
    /// descriptions are not available without an external JSON file.
    /// </summary>
    public static GodotApiCatalog CreateBuiltIn()
    {
        var classes = new Dictionary<string, GodotClassInfo>(StringComparer.Ordinal);

        // Merge PropertySignalCatalog entries (as signals)
        foreach (var (typeName, props) in PropertySignalCatalog.PropertySignals)
        {
            var classInfo = GetOrCreateClass(classes, typeName);
            var existingSignals = new HashSet<string>(
                classInfo.Signals.Select(s => s.Name), StringComparer.Ordinal);
            foreach (var (_, signalName) in props)
            {
                if (existingSignals.Add(signalName))
                {
                    classInfo.Signals.Add(new GodotSignalInfo { Name = signalName });
                }
            }
        }

        Log.Logger.Debug("Created built-in Godot API catalog with {Count} types", classes.Count);
        return new GodotApiCatalog(classes, godotVersion: null, isExternal: false);
    }

    /// <summary>
    /// Serializes a <see cref="GodotApiDocument"/> to a JSON file.
    /// </summary>
    public static void SaveToFile(GodotApiDocument apiDoc, string outputPath)
    {
        string? dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);

        string json = JsonSerializer.Serialize(apiDoc, s_jsonOptions);
        File.WriteAllText(outputPath, json);
        Log.Logger.Information("Saved Godot API catalog to {Path} ({Count} classes)",
            outputPath, apiDoc.Classes.Count);
    }

    // ══════════════════════════════════════════════════════
    //  Query: Property-Signal mapping (via PropertySignalCatalog)
    // ══════════════════════════════════════════════════════

    /// <summary>
    /// Returns the signal name that notifies when <paramref name="propertyName"/>
    /// changes on <paramref name="typeName"/>, or <c>null</c> if no mapping exists.
    /// Walks the inheritance chain.
    /// </summary>
    public string? GetSignalForProperty(string typeName, string propertyName)
    {
        // First check built-in catalog for explicit property→signal mappings
        string? builtIn = PropertySignalCatalog.GetSignalForProperty(typeName, propertyName);
        if (builtIn != null) return builtIn;

        // For external catalogs, we don't have explicit property→signal mappings
        // in the JSON (Godot docs don't directly link them). Fall through.
        return null;
    }

    /// <summary>
    /// Returns whether the given property on the given type has a known change signal.
    /// </summary>
    public bool IsObservable(string typeName, string propertyName)
        => GetSignalForProperty(typeName, propertyName) != null;

    // ══════════════════════════════════════════════════════
    //  Query: Theme overrides
    // ══════════════════════════════════════════════════════

    /// <summary>
    /// Returns the theme overrides declared directly on <paramref name="typeName"/>,
    /// or <c>null</c> if the type is not found or has no overrides.
    /// Key = override name, Value = data type category.
    /// </summary>
    public Dictionary<string, string>? GetThemeOverrides(string typeName)
    {
        if (!_classes.TryGetValue(typeName, out var classInfo)) return null;
        if (classInfo.ThemeOverrides.Count == 0) return null;

        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var ov in classInfo.ThemeOverrides)
            result[ov.Name] = ov.DataType;
        return result;
    }

    /// <summary>
    /// Returns merged theme overrides walking the inheritance chain.
    /// </summary>
    public Dictionary<string, string> GetMergedThemeOverrides(string typeName)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        string? current = typeName;
        while (current != null)
        {
            if (_classes.TryGetValue(current, out var classInfo))
            {
                foreach (var ov in classInfo.ThemeOverrides)
                {
                    result.TryAdd(ov.Name, ov.DataType);
                }
                current = classInfo.Inherits;
            }
            else
            {
                break;
            }
        }
        return result;
    }

    // ══════════════════════════════════════════════════════
    //  Query: Signals
    // ══════════════════════════════════════════════════════

    /// <summary>
    /// Returns signals declared directly on <paramref name="typeName"/>.
    /// </summary>
    public IReadOnlyList<GodotSignalInfo>? GetSignals(string typeName)
    {
        if (!_classes.TryGetValue(typeName, out var classInfo)) return null;
        return classInfo.Signals.Count > 0 ? classInfo.Signals : null;
    }

    /// <summary>
    /// Returns merged signals walking the inheritance chain.
    /// </summary>
    public List<GodotSignalInfo> GetMergedSignals(string typeName)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<GodotSignalInfo>();
        string? current = typeName;
        while (current != null)
        {
            if (_classes.TryGetValue(current, out var classInfo))
            {
                foreach (var sig in classInfo.Signals)
                {
                    if (seen.Add(sig.Name))
                        result.Add(sig);
                }
                current = classInfo.Inherits;
            }
            else
            {
                break;
            }
        }
        return result;
    }

    // ══════════════════════════════════════════════════════
    //  Query: Type info
    // ══════════════════════════════════════════════════════

    /// <summary>Returns the base type name, or <c>null</c> if not found.</summary>
    public string? GetBaseType(string typeName)
        => _classes.TryGetValue(typeName, out var c) ? c.Inherits : null;

    /// <summary>Returns the brief description, or <c>null</c> if not found.</summary>
    public string? GetBriefDescription(string typeName)
        => _classes.TryGetValue(typeName, out var c) ? c.BriefDescription : null;

    /// <summary>
    /// Returns the description of a specific property, or <c>null</c>.
    /// Walks the inheritance chain.
    /// </summary>
    public string? GetPropertyDescription(string typeName, string propertyName)
    {
        string? current = typeName;
        while (current != null)
        {
            if (_classes.TryGetValue(current, out var classInfo))
            {
                var prop = classInfo.Properties.FirstOrDefault(p => p.Name == propertyName);
                if (prop != null) return prop.Description;
                current = classInfo.Inherits;
            }
            else
            {
                break;
            }
        }
        return null;
    }

    /// <summary>
    /// Returns the description of a specific theme override, or <c>null</c>.
    /// Walks the inheritance chain.
    /// </summary>
    public string? GetThemeOverrideDescription(string typeName, string overrideName)
    {
        string? current = typeName;
        while (current != null)
        {
            if (_classes.TryGetValue(current, out var classInfo))
            {
                var ov = classInfo.ThemeOverrides.FirstOrDefault(o => o.Name == overrideName);
                if (ov != null) return ov.Description;
                current = classInfo.Inherits;
            }
            else
            {
                break;
            }
        }
        return null;
    }

    /// <summary>
    /// Converts a theme override <see cref="GodotThemeOverrideInfo.DataType"/> category
    /// to its CLR type name used in GUML property descriptors.
    /// </summary>
    public static string ThemeOverrideDataTypeToClrType(string dataType)
    {
        return dataType switch
        {
            "Color" => "Color",
            "Constant" => "int",
            "Font" => "Font",
            "FontSize" => "int",
            "Icon" => "Texture2D",
            "Style" => "StyleBox",
            _ => "Variant"
        };
    }

    // ══════════════════════════════════════════════════════
    //  API file discovery
    // ══════════════════════════════════════════════════════

    /// <summary>
    /// Returns the default user-global API data directory: <c>~/.guml/api/</c>.
    /// </summary>
    public static string GetUserApiDirectory()
    {
        string home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        return Path.Combine(home, ".guml", "api");
    }

    /// <summary>
    /// Returns the expected API file path for the given Godot version.
    /// Uses only major.minor (e.g. "4.6") for the filename.
    /// </summary>
    public static string GetApiFilePath(string godotVersion)
    {
        string majorMinor = ExtractMajorMinor(godotVersion);
        return Path.Combine(GetUserApiDirectory(), $"godot_api_{majorMinor}.json");
    }

    /// <summary>
    /// Attempts to find and load a Godot API catalog for the given version.
    /// Checks workspace-local override first, then user-global cache, then falls back to built-in.
    /// </summary>
    public static GodotApiCatalog FindAndLoad(string? godotVersion, string? workspaceRoot)
    {
        // 1. Workspace-local override
        if (!string.IsNullOrEmpty(workspaceRoot))
        {
            string localPath = Path.Combine(workspaceRoot, ".guml", "godot_api.json");
            var local = LoadFromFile(localPath);
            if (local != null) return local;
        }

        // 2. User-global cache
        if (!string.IsNullOrEmpty(godotVersion))
        {
            string globalPath = GetApiFilePath(godotVersion);
            var global = LoadFromFile(globalPath);
            if (global != null) return global;
        }

        // 3. Built-in fallback
        Log.Logger.Information("Using built-in Godot API catalog (no external file found)");
        return CreateBuiltIn();
    }

    /// <summary>
    /// Extracts the Godot SDK version from a .csproj file content.
    /// Matches patterns like <c>Godot.NET.Sdk/4.6.0</c>.
    /// </summary>
    public static string? ExtractGodotVersionFromCsproj(string csprojPath)
    {
        try
        {
            string content = File.ReadAllText(csprojPath);
            var match = Regex.Match(content, @"Godot\.NET\.Sdk/(\d+\.\d+(?:\.\d+)?(?:-[a-zA-Z0-9.]+)?)");
            if (match.Success)
            {
                return match.Groups[1].Value;
            }
        }
        catch (Exception ex)
        {
            Log.Logger.Debug(ex, "Failed to read csproj for version detection: {Path}", csprojPath);
        }
        return null;
    }

    // ══════════════════════════════════════════════════════
    //  Git clone + API generation
    // ══════════════════════════════════════════════════════

    /// <summary>
    /// Generates a Godot API JSON file by cloning the Godot source from GitHub
    /// and parsing doc/classes XML files.
    /// </summary>
    /// <param name="godotVersion">The version string (e.g. "4.6.0").</param>
    /// <param name="outputPath">Where to write the JSON file. If null, uses the default user path.</param>
    /// <param name="onProgress">Optional progress callback (stage, message).</param>
    /// <returns>The path to the generated file, or null on failure.</returns>
    public static async Task<string?> GenerateFromGitHubAsync(
        string godotVersion,
        string? outputPath = null,
        Action<string, string>? onProgress = null)
    {
        outputPath ??= GetApiFilePath(godotVersion);
        string tempDir = Path.Combine(Path.GetTempPath(), $"guml_godot_clone_{Guid.NewGuid():N}");

        try
        {
            // Determine tags to try
            string majorMinor = ExtractMajorMinor(godotVersion);
            string[] tagsToTry = [$"{godotVersion}-stable", $"{majorMinor}-stable"];
            bool usedFallback = false;

            onProgress?.Invoke("cloning", $"Cloning Godot {godotVersion} from GitHub...");

            bool cloned = false;
            foreach (string tag in tagsToTry)
            {
                if (await TryGitClone(tag, tempDir))
                {
                    cloned = true;
                    Log.Logger.Information("Successfully cloned Godot tag: {Tag}", tag);
                    break;
                }
                // Clean up failed attempt
                TryDeleteDirectory(tempDir);
            }

            if (!cloned)
            {
                // Fallback to master
                usedFallback = true;
                onProgress?.Invoke("warning",
                    $"Could not find tag for Godot {godotVersion}, falling back to master branch. " +
                    "API data may not exactly match your Godot version.");
                Log.Logger.Warning(
                    "No tag found for Godot {Version}, falling back to master branch", godotVersion);

                if (!await TryGitClone("master", tempDir))
                {
                    onProgress?.Invoke("error", "Failed to clone Godot repository. Check your network connection and Git installation.");
                    return null;
                }
            }

            // Parse
            string classesDir = Path.Combine(tempDir, "doc", "classes");
            if (!Directory.Exists(classesDir))
            {
                onProgress?.Invoke("error", $"doc/classes directory not found in cloned repository at {classesDir}");
                return null;
            }

            onProgress?.Invoke("parsing", "Parsing Godot XML documentation...");
            var apiDoc = GodotDocParser.ParseDirectory(classesDir, godotVersion);

            if (usedFallback)
            {
                apiDoc.GodotVersion = $"{godotVersion} (from master)";
            }

            onProgress?.Invoke("writing", $"Writing API data to {outputPath}...");
            SaveToFile(apiDoc, outputPath);

            onProgress?.Invoke("done",
                $"Successfully generated API data for Godot {godotVersion} ({apiDoc.Classes.Count} classes)");

            return outputPath;
        }
        catch (Exception ex)
        {
            Log.Logger.Error(ex, "Failed to generate Godot API from GitHub");
            onProgress?.Invoke("error", $"Failed to generate API data: {ex.Message}");
            return null;
        }
        finally
        {
            TryDeleteDirectory(tempDir);
        }
    }

    /// <summary>
    /// Generates a Godot API JSON file from a local Godot source directory.
    /// </summary>
    public static string? GenerateFromLocal(
        string godotSourcePath,
        string godotVersion,
        string? outputPath = null,
        Action<string, string>? onProgress = null)
    {
        outputPath ??= GetApiFilePath(godotVersion);

        string classesDir = Path.Combine(godotSourcePath, "doc", "classes");
        if (!Directory.Exists(classesDir))
        {
            onProgress?.Invoke("error", $"doc/classes directory not found at {classesDir}");
            return null;
        }

        onProgress?.Invoke("parsing", "Parsing Godot XML documentation...");
        var apiDoc = GodotDocParser.ParseDirectory(classesDir, godotVersion);

        onProgress?.Invoke("writing", $"Writing API data to {outputPath}...");
        SaveToFile(apiDoc, outputPath);

        onProgress?.Invoke("done",
            $"Successfully generated API data for Godot {godotVersion} ({apiDoc.Classes.Count} classes)");

        return outputPath;
    }

    // ══════════════════════════════════════════════════════
    //  Private helpers
    // ══════════════════════════════════════════════════════

    private static GodotClassInfo GetOrCreateClass(Dictionary<string, GodotClassInfo> classes, string name)
    {
        if (!classes.TryGetValue(name, out var info))
        {
            info = new GodotClassInfo();
            classes[name] = info;
        }
        return info;
    }

    /// <summary>Extracts "4.6" from "4.6.0" or "4.6.0-beta1".</summary>
    private static string ExtractMajorMinor(string version)
    {
        var match = Regex.Match(version, @"^(\d+\.\d+)");
        return match.Success ? match.Groups[1].Value : version;
    }

    private static async Task<bool> TryGitClone(string branchOrTag, string targetDir)
    {
        try
        {
            Directory.CreateDirectory(targetDir);

            // Step 1: sparse clone
            bool cloneResult = await RunGitAsync(
                $"clone --depth 1 --branch {branchOrTag} --filter=blob:none --sparse " +
                $"https://github.com/godotengine/godot.git \"{targetDir}\"",
                workingDir: null);

            if (!cloneResult) return false;

            // Step 2: sparse-checkout set
            bool sparseResult = await RunGitAsync(
                "sparse-checkout set doc/classes",
                workingDir: targetDir);

            return sparseResult;
        }
        catch (Exception ex)
        {
            Log.Logger.Debug(ex, "Git clone failed for branch/tag {Branch}", branchOrTag);
            return false;
        }
    }

    private static async Task<bool> RunGitAsync(string arguments, string? workingDir)
    {
        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = "git",
                Arguments = arguments,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            };
            if (workingDir != null) psi.WorkingDirectory = workingDir;

            using var process = Process.Start(psi);
            if (process == null) return false;

            // Read output to avoid deadlock
            string stderr = await process.StandardError.ReadToEndAsync();
            await process.WaitForExitAsync();

            if (process.ExitCode != 0)
            {
                Log.Logger.Debug("Git command failed (exit {Code}): git {Args}\n{Stderr}",
                    process.ExitCode, arguments, stderr);
                return false;
            }

            return true;
        }
        catch (Exception ex)
        {
            Log.Logger.Debug(ex, "Failed to run git {Args}", arguments);
            return false;
        }
    }

    private static void TryDeleteDirectory(string path)
    {
        try
        {
            if (Directory.Exists(path))
                Directory.Delete(path, recursive: true);
        }
        catch (Exception ex)
        {
            Log.Logger.Debug(ex, "Failed to clean up temp directory: {Path}", path);
        }
    }
}
