using GUML.Shared;

namespace GUML.SourceGenerator;

/// <summary>
/// Lightweight JSON serializer for <see cref="GumlApiCache"/>.
/// Targets netstandard2.0 without any external JSON library dependency.
/// </summary>
/// <remarks>
/// This serializer produces compact JSON output compatible with the format
/// generated by <c>GUML.ApiGenerator</c> (which uses System.Text.Json).
/// The output is consumed by GUML.LSP for completion and hover support.
/// </remarks>
internal static class GumlApiJsonSerializer
{
    /// <summary>
    /// Serializes a <see cref="GumlApiCache"/> to a JSON string.
    /// </summary>
    /// <param name="cache">The API cache to serialize.</param>
    /// <returns>A JSON string representation of the cache.</returns>
    public static string Serialize(GumlApiCache cache)
    {
        var sb = new StringBuilder();
        sb.Append('{');
        sb.Append("\"version\":");
        WriteString(sb, cache.Version);
        sb.Append(",\"generatedAt\":");
        WriteString(sb, cache.GeneratedAt.ToString("o"));
        sb.Append(",\"classes\":{");

        bool firstClass = true;
        foreach (var kvp in cache.Classes)
        {
            if (!firstClass) sb.Append(',');
            firstClass = false;

            WriteString(sb, kvp.Key);
            sb.Append(':');
            WriteClassInfo(sb, kvp.Value);
        }

        sb.Append('}');
        sb.Append('}');
        return sb.ToString();
    }

    private static void WriteClassInfo(StringBuilder sb, GumlClassInfo classInfo)
    {
        sb.Append('{');
        sb.Append("\"name\":");
        WriteString(sb, classInfo.Name);

        sb.Append(",\"baseType\":");
        if (classInfo.BaseType != null)
            WriteString(sb, classInfo.BaseType);
        else
            sb.Append("null");

        sb.Append(",\"description\":");
        WriteString(sb, classInfo.Description);

        sb.Append(",\"properties\":{");
        bool firstProp = true;
        foreach (var kvp in classInfo.Properties)
        {
            if (!firstProp) sb.Append(',');
            firstProp = false;

            WriteString(sb, kvp.Key);
            sb.Append(':');
            WritePropertyInfo(sb, kvp.Value);
        }
        sb.Append('}');
        sb.Append('}');
    }

    private static void WritePropertyInfo(StringBuilder sb, GumlPropertyInfo propInfo)
    {
        sb.Append('{');
        sb.Append("\"name\":");
        WriteString(sb, propInfo.Name);
        sb.Append(",\"type\":");
        WriteString(sb, propInfo.Type);
        sb.Append(",\"description\":");
        WriteString(sb, propInfo.Description);
        sb.Append('}');
    }

    private static void WriteString(StringBuilder sb, string value)
    {
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\b': sb.Append("\\b"); break;
                case '\f': sb.Append("\\f"); break;
                default:
                    if (c < ' ')
                        sb.AppendFormat("\\u{0:X4}", (int)c);
                    else
                        sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
    }
}
