using GUML;
using GUML.Shared;

namespace TestApplication.scripts.examples;

/// <summary>
/// 09 - Aliases &amp; Globals.
/// Demonstrates @ aliases (typed properties generated on the controller) and $controller chain access.
/// </summary>
[GumlController("res://gui/examples/09_aliases_and_globals.guml")]
public partial class AliasesAndGlobalsController : GuiController
{
    // --- Named nodes generated by Source Generator via @ aliases ---
    // public Label   GreetingLabel { get; internal set; }   // @greeting_label
    // public LineEdit NameInput    { get; internal set; }   // @name_input
    // public Button  SubmitBtn     { get; internal set; }   // @submit_btn

    // GUML: $controller.user_name  (=: reverse binding target from @name_input)
    public string UserName { get; set; } = "Alice";

    // GUML: $controller.display_name — what the greeting shows (updated on submit)
    public string DisplayName { get; private set; } = "Alice";

    // GUML: $controller.is_busy  (disables submit_btn while "processing")
    public bool IsBusy { get; } = false;

    // GUML: $controller.status_message
    public string StatusMessage { get; private set; } = "Ready";

    // GUML: $controller.submit_count
    public int SubmitCount { get; private set; }

    // GUML: $controller.data.profile.display_name (nested member chain access demo)
    public UserData Data { get; set; } = new();

    // GUML: #pressed: $controller.on_submit
    public void OnSubmit()
    {
        DisplayName = string.IsNullOrWhiteSpace(UserName) ? "World" : UserName;
        SubmitCount++;
        StatusMessage = $"Updated to \"{DisplayName}\"";
        OnPropertyChanged(nameof(DisplayName));
        OnPropertyChanged(nameof(StatusMessage));
        OnPropertyChanged(nameof(SubmitCount));
    }
}

public class UserData
{
    public UserProfile Profile { get; set; } = new();
}

public class UserProfile
{
    public string DisplayName { get; set; } = "Alice Johnson";
}
